//Data
const dataPelicula=[
    {   id:0,
        imagen:"/img/Peliculas/Coda.jpg",        
        titulo:"Coda",
        start: 8,
        anio: 2021,
        descripcion:"Como CODA (Hija de Adultos Sordos), Ruby es la única persona oyente de su familia sorda. Cuando el negocio pesquero de la familia se ve amenazado, Ruby se debate entre seguir su pasión en el Berklee College of Music y el miedo a abandonar a sus padres.",
        pagina:"pelicula1.html",
    },
    {   id:1,
        imagen:"/img/Peliculas/el_ultimo_traje.jpg",
        titulo:"El ultimo traje",
        start:7.5,
        anio:2017,
        descripcion:"Abraham Bursztein, un sastre judío de 88 años, huye de Buenos Aires a Polonia, donde se propone encontrar a un amigo que le salvó de una muerte segura al final de la Segunda Guerra Mundial. Tras siete décadas sin tener contacto con él, Abraham intentará encontrar a su viejo amigo y cumplir su promesa de volver algún día",
        pagina: "",
    },
    {   id:2,
        imagen:"/img/Peliculas/the_artist.jpg",
        titulo:"The artist",
        start:7.9 ,
        anio:2011,
        descripcion:"Cuando George, una superestrella del cine mudo, conoce a Peppy Miller, una bailarina, saltan chispas entre los dos. Sin embargo, tras la introducción del cine sonoro, su suerte cambia, afectando a su dinámica.",
        pagina:"",

    },
    {   id:3,
        imagen:"/img/Peliculas/whatever_works.jpg" ,
        titulo:"Whatever works",
        start:7.1,
        anio:2009,
        descripcion:"Un divorciado neoyorquino de mediana edad y misántropo entabla sorprendentemente una relación satisfactoria al estilo Pigmalión con una chica sureña mucho más joven y poco sofisticada.",
        pagina:"",


    },
    {id:4,
    imagen:"/img/Peliculas/12_angry_men.jpg",
    titulo:"12 Angry men",
    start:7.8,
    anio:1997,
    descripcion:"Doce hombres deben decidir el destino de uno cuando un miembro del jurado se opone a la decisión del jurado.",
    pagina:"",
    },
        {id:5,
        imagen:"/img/Peliculas/Fading_gigolo.jpg",
        titulo:"Fading Gigolo",
        start:6.2,
        anio:2013,
        descripcion:"Fioravante decide convertirse en Don Juan profesional para ganar dinero y ayudar a su amigo Murray, que no tiene dinero. Con Murray actuando como su 'manager', el dúo se ve rápidamente atrapado en las corrientes cruzadas del amor y el dinero.",
        pagina:"",

        },
        {id:6,
        imagen:"/img/Peliculas/See_No_Evil,_Hear_No_Evil.jpg",
        titulo:"See No Evil, Hear No Evil",
        start:6.8,
        anio:1989,
        descripcion:"Dave es sordo y Wally ciego. Son testigos de un asesinato, pero era Dave quien la miraba y Wally quien escuchaba.",
        pagina:"",

        },
        {id:7,
        imagen:"/img/Peliculas/La_guerre_du_feu.jpg",
        titulo:"La guerre du feu",
        start:7.3,
        anio:1981,
        descripcion:"Esta historia se desarrolla en la prehistoria, cuando tres miembros de una tribu buscan una nueva fuente de fuego.",
        pagina:"",

        },
        {id:8,
            imagen:"/img/Peliculas/Being_There.jpg",
            titulo:"Being There",
            start:7.9 ,
            anio:1971,
            descripcion:"Después de que la muerte de su jefe le obligue a abandonar el único hogar que ha conocido, un jardinero de mente sencilla y protegida se convierte en un improbable consejero de confianza de un poderoso magnate y en un infiltrado en la política de Washington.",
            pagina:"",

        },
        {id:9,
        imagen:"/img/Peliculas/Hardcore_Henry.jpg",
        titulo:"Hardcore Henry",
        start:6.7,
        anio:2015,
        descripcion:"Henry resucita de la muerte sin memoria, y debe salvar a su esposa de un señor de la guerra telequinético con un plan para bioingeniería de soldados.",
        pagina:"",

        },
]

const dataCortos=[
    {id:0,
    Titulo: 'Invention of love',
    anio: 2010,
    Director: 'Andrey Shushkov',
    Actores: 'nan',
    Sinopsis: 'Un joven que vive en una ciudad futurista retro, conoce a una chica que vive en el campo. Se enamoran. La chica se casa con el hombre, y juntos se instalan en la ciudad. Pronto ella empieza a darse cuenta de que en la ciudad no hay nada natural. Todo a su alrededor - un artificial, mecánico. Lo único que se conserva en su nuevo hogar, un recuerdo del mundo en el que nació y creció, la flor, se marchita poco a poco. Y ella también se marchita. Desesperado, el hombre crea una copia mecánica de su amada esposa.',
    imagen: "/img/Cortos/Invention_of_love.jpg",
    start: 6.4,
    link_video: `<iframe src="https://player.vimeo.com/video/22275870?h=387a30e6f0" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`,
    Pais: 'Rusia',
    clase:"flex-item1"},
    {id:1,
     Titulo: 'Inercia',
     anio: 2009,
     Director: 'Becho Lo Bianco',
     Actores: 'nan',
     Sinopsis: 'La inercia es la resistencia al cambio y la fuerza que hace que todas las cosas tiendan a mantenerse en el estado en que se encuentran. La inercia también actúa sobre las personas',
     imagen: "/img/Cortos/inercia.jpg",
     start: 9.0,
     link_video: `<iframe src="https://player.vimeo.com/video/85282955?h=acf16fc28d" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`,
     Pais: 'nan',
     clase:"flex-item1",
    },{id:2,
    Titulo: 'Fresh guacamole',
    anio: 2013,
    Director: 'PES',
    Actores: 'nan',
    Sinopsis: 'Fresh Guacamole es un divertido cortometraje surrealista de PES (Adam Pesapane) sobre un hombre que prepara guacamole con ingredientes poco habituales. El corto utiliza el stop motion y la continuidad para jugar con las expectativas del público, centrándose en el uso creativo de los objetos, su significado y sus funciones (una marca de Chaplin), así como en el lenguaje para sorprender al espectador.',
    imagen: "/img/Cortos/Fresh_guacamole.jpg",
    start: 6.0,
    link_video: `<iframe width="560" height="315" src="https://www.youtube.com/embed/5R2A7RG36MQ?si=w_P587EKxuwjvetU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
    Pais: 'nan',
    clase:"flex-item2",
    },
    {id:3,
    Titulo: 'Le Cafe - Oldela',
    anio: 2007,
    Director: 'Stephanie Marguerite & Emilie Tarascou',
    Actores: 'nan',
    Sinopsis: '«Le Café» de Oldelaf et Monsieur D. es una canción que muestra cómo el café puede convertirse en una especie de muleta en nuestras vidas diarias. Representa la necesidad de energía, rutina y una pequeña escapatoria de las presiones cotidianas. Aunque algunos de los eventos en la canción son un tanto exagerados, es un recordatorio de que debemos ser conscientes de cómo utilizamos las sustancias estimulantes en nuestras vidas.',
    imagen: "/img/Cortos/Le_cafe.jpg",
    start: 8.0,
    link_video: `<iframe width="560" height="315" src="https://www.youtube.com/embed/UGtKGX8B9hU?si=8YcHdCPvn1OyY1Ym" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
    Pais: 'Francia',
    clase:"flex-item2",
    }, 
    {id:4,
    Titulo: 'La Caja',
    anio: 'nan',
    Director: 'Becho Lo Bianco y Lorenzo mas Leal',
    Actores: 'nan',
    Sinopsis: 'Animación. Dos hombres en una caja Discuten sobre la posible existencia, ono, de un mundo mejor.',
    imagen: "/img/Cortos/La_caja.png",
    start: 9.0,
    link_video: `<iframe src="https://player.vimeo.com/video/317080134?h=5d96a5cbc3" width="640" height="468" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`,
    Pais: 'nan',
    clase:"flex-item2",
},
    {id:5,
    Titulo: 'La isla de las flores',
    anio: 1989.0,
    Director: 'Roberto Henkin e Sérgio Amon',
    Actores: 'nan',
    Sinopsis: 'Documental que muestra de forma satírica la cruda realidad de la sociedad brasileña de la época, la falta de conciencia, la miseria que lleva a la degradación del ser humano. Considerado uno de los cortometrajes documentales más importantes de la historia, ganador en Berlín y en otros festivales',
    imagen: "/img/Cortos/ilha_das_flores.jpg",
    start: 9.0,
    link_video: `<iframe width="560" height="315" src="https://www.youtube.com/embed/l_rVxAwiVvc?si=xSf170RaYBkFg4-1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
    Pais: 'nan',
    clase:"flex-item2",
},
    {id:6,
    Titulo: 'El empleo',
    anio: 2008.0,
    Director: "Santiago 'Bou' Grasso & Patricio Plaza",
    Actores: 'nan',
    Sinopsis: 'Que implica un dia de empleo',
    imagen: "/img/Cortos/el_empleo.jpg",
    start: 7.0,
    link_video: `<iframe width="560" height="315" src="https://www.youtube.com/embed/cxUuU1jwMgM?si=jkf5BuagVqHis-ak" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
    Pais: 'nan', 
    clase:"flex-item1",
}
]
